import LiveTreasury from "./live-treasury";

export default function Home() {
  return (<>
<header className="wrap nav"><a className="brand" href="#">GO<span>♥</span>GO</a><nav className="navlinks"><a href="#mission">初衷</a><a href="#transparency">公开账本</a><a className="pill" href="#verify">验证信息</a></nav></header>
  <main>
    <section className="wrap hero">
      <div><div className="eyebrow">Guangzhou Together · 09.14</div><h1>GO<span className="heart">♥</span>GO</h1><p className="lead">献给在广州大学城 9 月 14 日事件中受到影响的人。一个由社区独立发起、以公开记录为承诺的纪念项目。</p><p><a className="pill" href="https://four.meme/en/token/0xa1d63e8d513d2ff5de3c0b574f80d3be303cffff" target="_blank" rel="noopener noreferrer">查看 GOGO 代币 ↗</a></p></div>
      <aside className="hero-note"><strong>买入 3% · 卖出 3%</strong><p>Four.meme 税费信息显示，税费 100% 分配至指定收款钱包。受赠渠道核实前，资金不会以“已捐赠”名义对外宣传。</p></aside>
    </section>
    <section className="statement" id="mission"><div className="wrap statement-grid"><div className="kicker">Why we are here</div><div><h2>记住受影响的人，<br />把每一笔承诺留在链上。</h2><p>据广州番禺公安 2026 年 9 月 14 日通报，小谷围街发生持刀伤人事件，嫌疑人已被抓获，伤者经救治均无生命危险，案件仍在进一步侦办。GOGO 不代表受害者、商场、学校、警方或政府机构。</p></div></div></section>
    <section className="wrap section"><div className="section-head"><h2>资金如何流转</h2><p>公开税费设置与收款地址，逐步补充余额、捐赠交易及收款证明，供独立核验。</p></div><div className="flow"><article className="step"><span className="num">01 · TRADE</span><div><h3>产生交易税</h3><p>Four.meme 显示买入税率 3%、卖出税率 3%；具体适用交易以合约机制为准。</p></div><span className="arrow">→</span></article><article className="step"><span className="num">02 · TREASURY</span><div><h3>进入公开金库</h3><p>税费 100% 分配至下方公开的收款钱包，可通过 BscScan 查看链上记录。</p></div><span className="arrow">→</span></article><article className="step"><span className="num">03 · ASSISTANCE</span><div><h3>核实后捐出</h3><p>公开受赠方、交易哈希及可披露的收款证明。</p></div><span className="arrow">✓</span></article></div></section>
    <section className="wrap section" id="transparency"><div className="section-head"><h2>实时进度与账本</h2><p>金库余额自动读取 BNB Smart Chain；税费统计与捐赠证明分别标明核实状态。</p></div><LiveTreasury /><div className="ledger"><div className="metric"><small>平台显示已发送至收款钱包（2026-09-15 截图，非实时）</small><b>0.014423 BNB</b></div><div className="metric"><small>累计捐赠</small><b>待核实</b></div><div className="metric"><small>税费到账明细核对</small><b>待完成</b></div></div><div className="records"><div className="record"><strong>首次捐赠记录</strong><span>受赠渠道待核实</span><span>交易哈希待公布</span><em className="pending">待更新</em></div></div><div className="notice"><strong>透明度原则</strong><p>在出现经过核实的受赠渠道以前，金库中的金额只称为“待援助资金”，不称为“已捐款”，也不承诺可以直接转交给某位具体受害者。</p></div></section>
    <section className="wrap section" id="verify"><div className="section-head"><h2>验证信息</h2><p>税率与分配比例依据 Four.meme 截图；完整收款地址由项目方提供，与截图中的缩写一致，尚未独立核对合约收款配置。</p></div><div className="details"><div className="detail"><div className="detail-label">GOGO 合约地址</div><code><a href="https://bscscan.com/token/0xa1d63e8d513d2ff5de3c0b574f80d3be303cffff" target="_blank" rel="noopener noreferrer">0xa1d63e8d513d2ff5de3c0b574f80d3be303cffff</a></code><p><a href="https://four.meme/en/token/0xa1d63e8d513d2ff5de3c0b574f80d3be303cffff" target="_blank" rel="noopener noreferrer">在 Four.meme 查看 GOGO ↗</a></p></div><div className="detail"><div className="detail-label">Charity Treasury</div><code><a href="https://bscscan.com/address/0x92a1556D3d13a7816710dc47984893cE222535f2" target="_blank" rel="noopener noreferrer">0x92a1556D3d13a7816710dc47984893cE222535f2</a></code></div><div className="detail"><div className="detail-label">Network</div><code>BNB Smart Chain</code></div><div className="detail"><div className="detail-label">Tax</div><code>买入 3% / 卖出 3% · 税费 100% 分配至收款钱包</code></div></div></section>
  </main>
  <footer className="wrap footer"><div><strong>GOGO — Guangzhou Together</strong>Independent community initiative · 2026</div><div><strong>重要声明</strong>本项目并非官方募捐或投资产品，不与受害者、GOGO 新天地、任何高校、警方或政府机构存在隶属或授权关系。加密资产风险极高，请勿将购买代币视为捐赠的替代方式。</div></footer>
  </>);
}
